const {test}=require('node:test'),assert=require('node:assert/strict');
const {makeAccountHandler}=require('../server/account.cjs');
const {makeOperationsHandler}=require('../server/admin-operations.cjs');
const env={SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_SECRET_KEY:'sb_secret_fixture'},owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const response=()=>({setHeader(){},status(code){this.code=code;return this;},json(body){this.body=body;}});
const req=method=>({method,headers:{host:'dynamo.example.invalid',origin:'https://dynamo.example.invalid',cookie:'__Host-dynamo-user='+'a'.repeat(64)},query:{accountId:other}});
function fixtureFetch(calls,email='parent@example.invalid'){return async(url,options={})=>{const u=new URL(url);calls.push({url:u,options});let rows=[];if(u.pathname.endsWith('/dynamo_user_sessions'))rows=[{account:{id:owner,email,roster_member:false,roster_staff:true,wallet_pence:5000}}];else if(u.pathname.includes('/rpc/'))rows={bookingId:other};return {ok:true,status:200,json:async()=>rows};};}
test('account reads always scope private history to the session owner, ignoring requested account IDs',async()=>{const original=global.fetch,calls=[];try{global.fetch=fixtureFetch(calls);const res=response();await makeAccountHandler(env)(req('GET'),res);assert.equal(res.code,200);for(const call of calls.filter(c=>/dynamo_(gymnasts|purchases|transactions|wallet_ledger|event_bookings|party_bookings)$/.test(c.url.pathname)))assert.equal(call.url.searchParams.get('account_id'),'eq.'+owner);assert.equal(res.body.user.websiteAdmin,false);}finally{global.fetch=original;}});
test('a roster staff role does not grant wallet, refund or booking management access',async()=>{const original=global.fetch,calls=[];try{global.fetch=fixtureFetch(calls);const request=req('POST');request.body={action:'wallet',accountId:other,amountPence:1000,operationId:other,reason:'Fixture'};const res=response();await makeOperationsHandler(env)(request,res);assert.equal(res.code,403);assert.equal(calls.length,1);}finally{global.fetch=original;}});
test('booking price and account are computed server-side, ignoring browser-supplied prices and owner IDs',async()=>{const original=global.fetch,calls=[];try{global.fetch=fixtureFetch(calls);const request=req('POST');request.body={action:'book',kind:'event',targetId:other,gymnastId:other,useCredit:true,operationId:other,accountId:other,pricePence:0};const res=response();await makeAccountHandler(env)(request,res);assert.equal(res.code,201);const body=JSON.parse(calls.find(c=>c.url.pathname.includes('/rpc/book_dynamo_session')).options.body);assert.equal(body.p_account,owner);assert.equal(body.pricePence,undefined);}finally{global.fetch=original;}});
