begin;
set local role service_role;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();actor uuid:=gen_random_uuid();g uuid:=gen_random_uuid();g2 uuid:=gen_random_uuid();e uuid:=gen_random_uuid();e2 uuid:=gen_random_uuid();restricted uuid:=gen_random_uuid();party uuid:=gen_random_uuid();otherparty uuid:=gen_random_uuid();op uuid:=gen_random_uuid();op2 uuid:=gen_random_uuid();codeid uuid:=gen_random_uuid();codeid2 uuid:=gen_random_uuid();result jsonb;result2 jsonb;booking uuid;booking2 uuid;tx uuid;balance bigint;n integer;
begin
 insert into public.dynamo_accounts(id,email,roster_member) values(a,'fixture-a-'||a||'@example.invalid',true),(b,'fixture-b-'||b||'@example.invalid',false),(actor,'fixture-admin-'||actor||'@example.invalid',false);
 insert into public.dynamo_gymnasts(id,account_id,source_id,first_name,last_name,date_of_birth,groups,active) values(g,a,'manual:'||g,'Fixture','One','2020-01-01',array['gymini'],true),(g2,b,'manual:'||g2,'Fixture','Two','2020-01-01','{}',false);
 result:=public.request_dynamo_code(codeid,'fixture-a-'||a||'@example.invalid',repeat('a',64),repeat('b',64));if not (result->>'ok')::boolean then raise exception 'code request failed';end if;
 for n in 1..5 loop result:=public.verify_dynamo_code(codeid,repeat('c',64),repeat('d',64));if (result->>'ok')::boolean then raise exception 'wrong code accepted';end if;end loop;
 result:=public.verify_dynamo_code(codeid,repeat('b',64),repeat('d',64));if result->>'error'<>'OTP_EXPIRED' then raise exception 'attempt limit failed';end if;
 result:=public.request_dynamo_code(gen_random_uuid(),'fixture-a-'||a||'@example.invalid',repeat('a',64),repeat('b',64));if result->>'error'<>'LOGIN_RATE_LIMIT' then raise exception 'resend rate limit failed';end if;
 result:=public.request_dynamo_code(codeid2,'fixture-b-'||b||'@example.invalid',repeat('a',64),repeat('b',64));result:=public.verify_dynamo_code(codeid2,repeat('b',64),repeat('d',64));if not (result->>'ok')::boolean or result->>'accountId'<>b::text then raise exception 'account identity lost';end if;
 result:=public.verify_dynamo_code(codeid2,repeat('b',64),repeat('e',64));if (result->>'ok')::boolean then raise exception 'code reused';end if;
 result:=public.adjust_dynamo_wallet(a,actor,2000,'Fixture credit',op);result:=public.adjust_dynamo_wallet(a,actor,2000,'Fixture credit',op);if (result->>'balance')::bigint<>2000 then raise exception 'duplicate credit applied';end if;
 begin perform public.adjust_dynamo_wallet(a,actor,-2001,'Fixture removal',gen_random_uuid());raise exception 'negative wallet accepted';exception when others then if sqlerrm<>'INSUFFICIENT_CREDIT' then raise;end if;end;
 perform public.adjust_dynamo_wallet(b,actor,2000,'Fixture credit',gen_random_uuid());
 insert into public.dynamo_events(id,details) values(e,jsonb_build_object('name','Fixture session','date','2030-01-01','time','10:00','capacity',1,'memberPriceCents',1000,'nonMemberPriceCents',1200,'status','Published','audience','everyone','allowedGroups','[]'::jsonb)),(e2,jsonb_build_object('name','Fixture destination','date','2030-01-02','time','10:00','capacity',1,'memberPriceCents',1000,'nonMemberPriceCents',1000,'status','Published','audience','everyone','allowedGroups','[]'::jsonb)),(restricted,jsonb_build_object('name','Fixture restricted','date','2030-01-03','time','10:00','capacity',1,'memberPriceCents',1000,'nonMemberPriceCents',1000,'status','Published','audience','groups','allowedGroups',jsonb_build_array('womens_squad')));
 begin perform public.book_dynamo_session('event',e,a,g2,true,gen_random_uuid());raise exception 'another account gymnast accepted';exception when others then if sqlerrm<>'GYMNAST_NOT_FOUND' then raise;end if;end;
 begin perform public.book_dynamo_session('event',restricted,a,g,true,gen_random_uuid());raise exception 'ineligible gymnast accepted';exception when others then if sqlerrm<>'SESSION_INELIGIBLE' then raise;end if;end;
 begin perform public.book_dynamo_session('event',e,a,g,false,gen_random_uuid());raise exception 'unpaid booking accepted';exception when others then if sqlerrm<>'CARD_PAYMENT_NOT_CONNECTED' then raise;end if;end;
 result:=public.book_dynamo_session('event',e,a,g,true,op2);booking:=(result->>'bookingId')::uuid;result2:=public.book_dynamo_session('event',e,a,g,true,op2);if result2->>'bookingId'<>booking::text then raise exception 'booking retry duplicated';end if;
 select wallet_pence into balance from public.dynamo_accounts where id=a;if balance<>1000 then raise exception 'incorrect booking debit';end if;
 result2:=public.book_dynamo_session('event',e2,b,g2,true,gen_random_uuid());booking2:=(result2->>'bookingId')::uuid;
 begin perform public.manage_dynamo_booking('event',booking,actor,'move',e2,null,null,gen_random_uuid());raise exception 'overbooking accepted';exception when others then if sqlerrm<>'SESSION_FULL' then raise;end if;end;
 perform public.manage_dynamo_booking('event',booking2,actor,'cancel',null,null,null,gen_random_uuid());perform public.manage_dynamo_booking('event',booking,actor,'move',e2,null,null,gen_random_uuid());
 if (select event_id from public.dynamo_event_bookings where id=booking)<>e2 then raise exception 'move failed';end if;
 select id into tx from public.dynamo_transactions where purchase_id=(select purchase_id from public.dynamo_event_bookings where id=booking);
 op:=gen_random_uuid();perform public.refund_dynamo_wallet_payment(tx,actor,300,'Fixture partial refund',op);perform public.refund_dynamo_wallet_payment(tx,actor,300,'Fixture partial refund',op);
 if (select wallet_pence from public.dynamo_accounts where id=a)<>1300 then raise exception 'duplicate refund applied';end if;
 begin perform public.refund_dynamo_wallet_payment(tx,actor,701,'Fixture excessive refund',gen_random_uuid());raise exception 'excess refund accepted';exception when others then if sqlerrm<>'INVALID_REFUND' then raise;end if;end;
 perform public.refund_dynamo_wallet_payment(tx,actor,700,'Fixture remaining refund',gen_random_uuid());if (select status from public.dynamo_transactions where id=tx)<>'refunded' or (select wallet_pence from public.dynamo_accounts where id=a)<>2000 then raise exception 'full refund failed';end if;
 perform public.manage_dynamo_booking('event',booking,actor,'cancel',null,null,null,gen_random_uuid());if (select count(*) from public.dynamo_purchases where account_id=a)<>1 then raise exception 'purchase history lost';end if;
 insert into public.dynamo_parties(id,details) values(party,jsonb_build_object('name','Fixture birthday','date','2030-02-01','time','15:30','room','Big gym','status','Confirmed','guests',20,'memberPriceCents',0,'nonMemberPriceCents',0)),(otherparty,jsonb_build_object('name','Other party','date','2030-02-02','time','14:00','room','Big gym','status','Confirmed','guests',20,'memberPriceCents',0,'nonMemberPriceCents',0));
 result:=public.book_dynamo_session('party',party,a,g,false,gen_random_uuid());booking:=(result->>'bookingId')::uuid;
 begin perform public.manage_dynamo_booking('party',booking,actor,'move',null,'2030-02-02','13:00',gen_random_uuid());raise exception 'party overlap accepted';exception when others then if sqlerrm<>'PARTY_SLOT_TAKEN' then raise;end if;end;
 perform public.manage_dynamo_booking('party',booking,actor,'move',null,'2030-02-03','13:00',gen_random_uuid());if (select details->>'time' from public.dynamo_parties where id=party)<>'13:00' then raise exception 'party move failed';end if;
end;$$;
rollback;
select 'OTP limits, account identity, wallet debits/refunds, moves, capacity, ownership and history verified; fixtures rolled back' as result;
