const {test}=require('node:test'),assert=require('node:assert/strict');
const {settings,verifyEmail,sendEmail}=require('../server/email.cjs');
const {makeEmailStatusHandler}=require('../server/email-status.cjs');
const env={SMTP_HOST:'smtp.gmail.com',SMTP_PORT:'465',SMTP_USER:'original@example.invalid',SMTP_PASSWORD:'abcd efgh ijkl mnop',EMAIL_FROM:'notifications@example.invalid',EMAIL_FROM_NAME:'Dynamo Gymnastics',SYNC_SCHEDULE_SECRET:'fictional-diagnostic-secret-long-enough'};
const res=()=>({setHeader(){},status(value){this.statusCode=value;return this;},json(value){this.body=value;}});
test('Google alias sender uses original login, encrypted transport and no credential logging',()=>{const c=settings(env);assert.equal(c.transport.auth.user,env.SMTP_USER);assert.equal(c.from.address,env.EMAIL_FROM);assert.equal(c.transport.auth.pass,'abcdefghijklmnop');assert.equal(c.transport.secure,true);assert.equal(c.transport.debug,false);assert.equal(c.transport.disableFileAccess,true);assert.equal(settings({...env,SMTP_PORT:'587'}).transport.requireTLS,true);assert.throws(()=>settings({...env,SMTP_PASSWORD:'abcd_efgh_ijkl_mnop'}),/EMAIL_NOT_CONFIGURED/);});
test('SMTP connection check sends no messages and sanitises authentication failures',async()=>{let closed=0;await verifyEmail(env,()=>({async verify(){},close(){closed++;},sendMail(){assert.fail('must not send');}}));assert.equal(closed,1);await assert.rejects(()=>verifyEmail(env,()=>({async verify(){throw Object.assign(new Error('secret login response'),{code:'EAUTH'});},close(){}})),error=>error.code==='EMAIL_AUTH_FAILED'&&!error.message.includes('secret'));});
test('mail content cannot override sender or add extra recipients, and transport is closed',async()=>{let closed=false;await sendEmail({to:'recipient@example.invalid',subject:'Confirmation',text:'Details',from:'attacker@example.invalid'},env,()=>({async sendMail(message){assert.equal(message.from.address,env.EMAIL_FROM);assert.equal(message.to,'recipient@example.invalid');return {accepted:[message.to]};},close(){closed=true;}}));assert.equal(closed,true);await assert.rejects(()=>sendEmail({to:'one@example.invalid,two@example.invalid',subject:'x',text:'x'},env),/EMAIL_INVALID_MESSAGE/);});
test('email diagnostics require authentication and never expose SMTP settings',async()=>{let calls=0;const handler=makeEmailStatusHandler(env,async()=>{calls++;return {ok:true,smtpAuthenticated:true,emailSent:false};});const denied=res();await handler({method:'POST',headers:{}},denied);assert.equal(denied.statusCode,401);assert.equal(calls,0);const response=res();await handler({method:'POST',headers:{authorization:'Bearer '+env.SYNC_SCHEDULE_SECRET}},response);assert.equal(response.statusCode,200);assert.equal(response.body.emailSent,false);assert.equal(JSON.stringify(response.body).includes(env.SMTP_USER),false);});

test('all test emails have a fixed approved recipient and ignore supplied content',async()=>{const {sendTestEmail,TEST_RECIPIENT}=require('../server/email.cjs');assert.equal(TEST_RECIPIENT,'freddiemullenuk@icloud.com');await sendTestEmail(env,()=>({async sendMail(message){assert.equal(message.to,TEST_RECIPIENT);assert.match(message.subject,/connection test/);return {accepted:[TEST_RECIPIENT]};},close(){}}));let sent=0;const handler=makeEmailStatusHandler(env,async()=>({ok:true}),async()=>{sent++;});const response=res();await handler({method:'POST',headers:{authorization:'Bearer '+env.SYNC_SCHEDULE_SECRET},body:{action:'send-test',to:'someone-else@example.invalid'}},response);assert.equal(sent,1);assert.equal(response.body.emailSent,true);});
